server:
  port: 8081
  compression:
    enabled: true
    mime-types: text/html, text/xml, text/plain,text/css, text/javascript, application/javascript, application/json,application/xml
    min-response-size: 2048

spring:
  datasource:
    username: 填写数据库用户名
    password: 填写数据库密码
    url: 填写数据库url
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.shadowingszy.notebook.entity

#showSql
logging:
  level:
    com:
      shadowingszy:
        notebook:
          mapper: debug

